apiVersion: v1 # Specifies the API version
kind: Service # Specifies the kind of resource to create
metadata: # Metadata of the service
  name: k8s-web-application-service # Name of the service
spec:
  selector: # Selector to match the pods
    app: k8s-web-application # Label of the service
  ports: # Ports to expose
  - protocol: TCP # Protocol of the port
    port: 80 # Port of the service
    targetPort: 3008 # Target port of the service
    nodePort: 30080 # Node port of the service
  type: NodePort # Type of the service